# .readthedocs.yaml — v2 config
version: 2                  

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"            

sphinx:
  configuration: docs/source/conf.py  


python:
  install:
    # install your package in editable mode (optional but common)
    - method: pip
      path: .
      editable: true
    # doc‑only dependencies
    - requirements: docs/requirements.txt
