# .readthedocs.yaml — v2 config
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    post_install:
      - python -m pip install --upgrade pip
      - python -m pip install sphinx-rtd-theme

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - method: pip
      path: .
