# .readthedocs.yaml — v2 config
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    # Install your package in editable mode + extra dependencies
    - method: pip
      path: .
      extra_requirements:
        - sphinx
        - sphinx-rtd-theme
