# .readthedocs.yaml — v2 config
version: 2                  

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"            

sphinx:
  configuration: docs/source/conf.py  

python:
  install:
    # Install your package in editable mode (so autodoc can import it)
    - method: pip
      path: .
    # Install the Sphinx ReadTheDocs theme directly
    - method: pip
      dependencies:
        - sphinx
        - sphinx-rtd-theme
